Repository Roberto640Alvarado/SmugTicket2024, pull requests merged in 2024-06, with the labels that each got.

#9 :bricks: Agregando Entidad de la tabla Ubicacion
  Server/api/src/main/java/com/example/demo/model/entities/Ubicacion.java
  Server/api/src/main/resources/application.properties
Labels: review

#10 :memo: Tabla ubicacion en BD agregada
  Data/Script-Smugtickets.sql
Labels: documentation

#11 :sparkles: Agregando endpoint sobre consultas de la Ubicacion
  Server/api/src/main/java/com/example/demo/controllers/UbicacionController.java
  Server/api/src/main/java/com/example/demo/repository/UbicacionRepository.java
  Server/api/src/main/java/com/example/demo/services/UbicacionService.java
  Server/api/src/main/java/com/example/demo/services/implementation/UbicacionImpl.java
  Server/api/src/main/java/com/example/demo/utils/WebSecurityConfiguration.java
Labels: review

#12 Dev team18
  Data/Script-Smugtickets.sql
  Server/api/src/main/java/com/example/demo/controllers/UbicacionController.java
  Server/api/src/main/java/com/example/demo/model/entities/Ubicacion.java
  Server/api/src/main/java/com/example/demo/repository/UbicacionRepository.java
  Server/api/src/main/java/com/example/demo/services/UbicacionService.java
  Server/api/src/main/java/com/example/demo/services/implementation/UbicacionImpl.java
  Server/api/src/main/java/com/example/demo/utils/WebSecurityConfiguration.java
  Server/api/src/main/resources/application.properties
Labels: review

#15 :beers: He añadido los servicios de ubicación
  Client/smug-tickets/src/services/Ubication/UbicationService.js
Labels: enhancement

#17 :sparkles: Modificando y agregando formularios de ubicacion
  Client/smug-tickets/.env
  Client/smug-tickets/package-lock.json
  Client/smug-tickets/src/pages/admin/CreatEvent.jsx
  Client/smug-tickets/src/pages/admin/EditEvent.jsx
  Client/smug-tickets/src/pages/admin/NewLocation.jsx
  Client/smug-tickets/src/pages/admin/ViewEvent.jsx
  Client/smug-tickets/src/pages/user/ViewEvent.jsx
  Client/smug-tickets/src/services/Auth/AuthService.js
  Client/smug-tickets/src/services/Auth/RolService.js
  Client/smug-tickets/src/services/Category/CategoryService.js
  Client/smug-tickets/src/services/Event/EventService.js
  Client/smug-tickets/src/services/Locality/LocalityService.js
  Client/smug-tickets/src/services/Publico/PublicService.js
  Client/smug-tickets/src/services/Ticket/TicketService.js
  Client/smug-tickets/src/services/Users/UsersService.js
Labels: review
